### ISSUE TITLE
Async 'process' callback argument order wrong

### ISSUE THREAD

**Issue by sfrdmn** [wooorm/unified#6]
According to the documentation, when calling `process` async, it will call its callback with the arguments `(err, result, file)`. It actually calls it with the arguments `(err, file, result)` [link](https://github.com/wooorm/unified/blob/32b917f97b1ce4f46dd180894651cc5352f40362/index.js#L258)

The same mistake is in remark's documentation

**Comment by wooorm** [comment]
Whoops, sorry for the confusion, thanks for letting me know!

**Comment by wooorm** [comment]
Maybe it would be better to drop the `doc` from both the sync and the async `process`, instead returning a file for both. One could still `String(file)` to get the doc, and access to messages and other information would be accessible synchronously!
